# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.53.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Bumps version number and deploys test app to Hockey"
  lane :deploy do
    increment_version_number({
        xcodeproj: './UI/CartrawlerSDK.xcodeproj',
    })

    increment_version_number({
        xcodeproj: './TestApp/TestApp.xcodeproj',
    })

    match
    sigh

    gym(scheme: "BuildTestApp",
        configuration: "Debug",
        export_method: "development"
    )

    hockey(
       api_token: "bd4247b5ba73405ab0d7b47b3517748f",
       notify: '1',
    )

    clean_build_artifacts

    message = "Version  of iOS Generic App now available"
    message.insert(8 , get_version_number(xcodeproj: './UI/CartrawlerSDK.xcodeproj'))

    slack(
        message: message,
        payload: {
            'Download Link' => lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK],
        },
        default_payloads: [],
        slack_url: "https://hooks.slack.com/services/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"
    )

  end

  after_all do |lane|
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
