# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.53.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

    desc "Build universal library"
    lane :build_library do
        xcodebuild(
            scheme: 'CartrawlerSDK',
            configuration: 'Release',
            derivedDataPath: '../../temp_builds',
        )
        xcodebuild(
            scheme: 'CartrawlerSDK',
            configuration: 'Release',
            destination: 'platform=iOS Simulator,name=iPhone 7',
            derivedDataPath: '../../temp_builds',
        )

        clean_build_artifacts
    end

    desc "Increments build and deploys test app to Hockey"
    lane :deploy_build do
        ensure_git_status_clean
        increment_build_number(xcodeproj: './UI/CartrawlerSDK.xcodeproj')
        commit_version_bump(xcodeproj: './UI/CartrawlerSDK.xcodeproj')

        match
        sigh

        gym(scheme: "BuildTestApp",
            configuration: "Debug",
            export_method: "development"
        )

        hockey(
            api_token: "dfca46ae53374a95a3168e630e8fcbfb",
            notify: '0',
            notes: changelog_from_git_commits,
        )

        clean_build_artifacts

        version = get_version_number(xcodeproj: './UI/CartrawlerSDK.xcodeproj')
        build = get_build_number(xcodeproj: './UI/CartrawlerSDK.xcodeproj')
        message = "Version " + version + " (" + build + ") " + "of iOS Generic App now available"

        slack(
            message: message,
            payload: {
                'Download Link' => lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK],
                'New in this build' => changelog_from_git_commits
            },
            default_payloads: [],
            #slack_url: "https://hooks.slack.com/services/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"
            slack_url: "https://hooks.slack.com/services/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"
        )

        tagmessage = "- Incremented build number (" + build + ")"
        add_git_tag(
            message: tagmessage,
        )
    end

  desc "Bumps version number and deploys test app to Hockey"
  lane :deploy do
    increment_version_number({
        xcodeproj: './UI/CartrawlerSDK.xcodeproj',
    })

    increment_version_number({
        xcodeproj: './TestApp/TestApp.xcodeproj',
    })

    match
    sigh

    gym(scheme: "BuildTestApp",
        configuration: "Debug",
        export_method: "development"
    )

    hockey(
       api_token: "dfca46ae53374a95a3168e630e8fcbfb",
       notify: '1',
    )

    clean_build_artifacts

    message = "Version  of iOS Generic App now available"
    message.insert(8 , get_version_number(xcodeproj: './UI/CartrawlerSDK.xcodeproj'))

    slack(
        message: message,
        payload: {
            'Download Link' => lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK],
        },
        default_payloads: [],
        slack_url: "https://hooks.slack.com/services/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"
    )

  end

  after_all do |lane|
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
