# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.53.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Bumps version number and deploys test app to Hockey"
  lane :deploy do
    ensure_git_status_clean

    increment_version_number({
        xcodeproj: './UI/CartrawlerSDK.xcodeproj',
    })

    increment_version_number({
        xcodeproj: './TestApp/TestApp.xcodeproj',
    })

    gym(scheme: "BuildTestApp")

    hockey(
        api_token: "bd4247b5ba73405ab0d7b47b3517748f",
        notes: "Changelog",
        notify: "1",
    )

  end

  after_all do |lane|
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
