//
//  CTBannerEdge.h
//
//  Created on 7/26/17.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;

@interface CTBannerEdge : NSObject

#pragma mark - Resizing Behavior

typedef enum : NSInteger {
    CTBannerEdgeResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    CTBannerEdgeResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    CTBannerEdgeResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    CTBannerEdgeResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
} CTBannerEdgeResizingBehavior;

extern CGRect CTBannerEdgeResizingBehaviorApply(CTBannerEdgeResizingBehavior behavior, CGRect rect, CGRect target);

+ (void)drawArtboardWithFrame:(CGRect)targetFrame
                     resizing:(CTBannerEdgeResizingBehavior)resizing
                 primaryColor:(UIColor *)primaryColor;


@end
