//
//  CTCodedImages.h
//
//  Created on 02/08/2017.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface CTCodedImages : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger {
    CTCodedImagesResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    CTCodedImagesResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    CTCodedImagesResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    CTCodedImagesResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
} CTCodedImagesResizingBehavior;

extern CGRect CTCodedImagesResizingBehaviorApply(CTCodedImagesResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1

+ (void)drawTickWithFrame:(CGRect)targetFrame resizing:(CTCodedImagesResizingBehavior)resizing primaryColor:(UIColor *)primaryColor;

+ (void)drawCloudBackgroundWithFrame:(CGRect)targetFrame resizing:(CTCodedImagesResizingBehavior)resizing primaryColor:(UIColor *)primaryColor;

+ (void)drawCarWithFrame:(CGRect)targetFrame resizing:(CTCodedImagesResizingBehavior)resizing primaryColor:(UIColor *)primaryColor;

+ (void)drawInsuranceWithFrame:(CGRect)targetFrame resizing:(CTCodedImagesResizingBehavior)resizing primaryColor:(UIColor *)primaryColor;

+ (void)drawMapWithFrame:(CGRect)targetFrame resizing:(CTCodedImagesResizingBehavior)resizing primaryColor:(UIColor *)primaryColor;

+ (void)drawLock2WithFrame:(CGRect)targetFrame resizing:(CTCodedImagesResizingBehavior)resizing primaryColor:(UIColor *)primaryColor;

+ (void)drawSearchWithFrame:(CGRect)targetFrame resizing:(CTCodedImagesResizingBehavior)resizing primaryColor:(UIColor *)primaryColor;

+ (void)drawHeadsetWithFrame:(CGRect)targetFrame resizing:(CTCodedImagesResizingBehavior)resizing primaryColor:(UIColor *)primaryColor;

+ (void)drawCreditCardWithFrame:(CGRect)targetFrame resizing:(CTCodedImagesResizingBehavior)resizing primaryColor:(UIColor *)primaryColor;


@end
