//
//  CTSplashCar.m
//
//  Created on 7/25/17.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;
#import "CTSplashCar.h"

@implementation CTSplashCar

#pragma mark - Canvas Drawings

+ (void)drawArtboardWithFrame:(CGRect)targetFrame resizing:(CTSplashCarResizingBehavior)resizing primaryColor:(UIColor *)primaryColor {
    //! General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //! Resize to Target Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = CTSplashCarResizingBehaviorApply(resizing, CGRectMake(0, 0, 159, 152), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 159, resizedFrame.size.height / 152);
    
    //! Car illustration Generic
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 7, 4);
        
        //! Oval
        UIBezierPath *oval = [UIBezierPath bezierPathWithOvalInRect:CGRectMake(0, 0, 144, 144)];
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 0.36, 0.36);
        [[UIColor colorWithWhite:0.89 alpha:1] setFill];
        [oval fill];
        CGContextSaveGState(context);
        oval.lineWidth = 12;
        CGContextBeginPath(context);
        CGContextAddPath(context, oval.CGPath);
        CGContextEOClip(context);
        [UIColor.whiteColor setStroke];
        [oval stroke];
        CGContextRestoreGState(context);
        CGContextRestoreGState(context);
        
        //! Oval (Outline Mask)
        CGContextSaveGState(context);
        [oval applyTransform:CGAffineTransformMakeTranslation(0.36, 0.36)];
        [oval addClip];
        
        //! Car illustration_ Generic
        {
            CGContextSaveGState(context);
            CGContextTranslateCTM(context, 2.01, 2.31);
            
            //! Fill 1
            UIBezierPath *fill1 = [UIBezierPath bezierPath];
            [fill1 moveToPoint:CGPointMake(94.81, 100.59)];
            [fill1 addCurveToPoint:CGPointMake(114.77, 57.22) controlPoint1:CGPointMake(107.02, 90.1) controlPoint2:CGPointMake(114.77, 74.57)];
            [fill1 addCurveToPoint:CGPointMake(57.39, 0) controlPoint1:CGPointMake(114.77, 25.62) controlPoint2:CGPointMake(89.08, 0)];
            [fill1 addCurveToPoint:CGPointMake(0, 57.22) controlPoint1:CGPointMake(25.69, 0) controlPoint2:CGPointMake(0, 25.62)];
            [fill1 addCurveToPoint:CGPointMake(19.97, 100.59) controlPoint1:CGPointMake(0, 74.57) controlPoint2:CGPointMake(7.75, 90.1)];
            [fill1 addLineToPoint:CGPointMake(94.81, 100.59)];
            [fill1 closePath];
            [fill1 moveToPoint:CGPointMake(94.81, 100.59)];
            CGContextSaveGState(context);
            CGContextTranslateCTM(context, 12.69, 11.78);
            fill1.usesEvenOddFillRule = YES;
            [UIColor.whiteColor setFill];
            [fill1 fill];
            CGContextRestoreGState(context);
            
            //! Fill 3
            UIBezierPath *fill3 = [UIBezierPath bezierPath];
            [fill3 moveToPoint:CGPointMake(8.25, 71.62)];
            [fill3 addLineToPoint:CGPointMake(83.09, 71.62)];
            [fill3 addCurveToPoint:CGPointMake(103.06, 28.25) controlPoint1:CGPointMake(95.31, 61.12) controlPoint2:CGPointMake(103.06, 45.59)];
            [fill3 addCurveToPoint:CGPointMake(95.57, 0) controlPoint1:CGPointMake(103.06, 17.97) controlPoint2:CGPointMake(100.33, 8.34)];
            [fill3 addCurveToPoint:CGPointMake(0, 62.88) controlPoint1:CGPointMake(53.99, 3.22) controlPoint2:CGPointMake(18.44, 27.87)];
            [fill3 addCurveToPoint:CGPointMake(8.25, 71.62) controlPoint1:CGPointMake(2.44, 66.08) controlPoint2:CGPointMake(5.21, 69)];
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.1);
            CGContextBeginTransparencyLayer(context, nil);
            {
                CGContextTranslateCTM(context, 24.41, 40.75);
                fill3.usesEvenOddFillRule = YES;
                [UIColor.blackColor setFill];
                [fill3 fill];
            }
            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
            
            //! Fill 5
            UIBezierPath *fill5 = [UIBezierPath bezierPath];
            [fill5 moveToPoint:CGPointMake(69.56, 0)];
            [fill5 addCurveToPoint:CGPointMake(0, 69.36) controlPoint1:CGPointMake(31.2, 0) controlPoint2:CGPointMake(0, 31.12)];
            [fill5 addCurveToPoint:CGPointMake(24.2, 121.92) controlPoint1:CGPointMake(0, 89.56) controlPoint2:CGPointMake(8.82, 108.72)];
            [fill5 addCurveToPoint:CGPointMake(28.09, 123.36) controlPoint1:CGPointMake(25.28, 122.85) controlPoint2:CGPointMake(26.66, 123.36)];
            [fill5 addLineToPoint:CGPointMake(111.03, 123.36)];
            [fill5 addCurveToPoint:CGPointMake(114.92, 121.92) controlPoint1:CGPointMake(112.45, 123.36) controlPoint2:CGPointMake(113.84, 122.85)];
            [fill5 addCurveToPoint:CGPointMake(139.11, 69.36) controlPoint1:CGPointMake(130.29, 108.72) controlPoint2:CGPointMake(139.11, 89.56)];
            [fill5 addCurveToPoint:CGPointMake(69.56, 0) controlPoint1:CGPointMake(139.11, 31.12) controlPoint2:CGPointMake(107.91, 0)];
            [fill5 moveToPoint:CGPointMake(69.56, 5.95)];
            [fill5 addCurveToPoint:CGPointMake(133.15, 69.36) controlPoint1:CGPointMake(104.68, 5.95) controlPoint2:CGPointMake(133.15, 34.34)];
            [fill5 addCurveToPoint:CGPointMake(111.03, 117.42) controlPoint1:CGPointMake(133.15, 88.58) controlPoint2:CGPointMake(124.57, 105.79)];
            [fill5 addLineToPoint:CGPointMake(28.09, 117.42)];
            [fill5 addCurveToPoint:CGPointMake(5.96, 69.36) controlPoint1:CGPointMake(14.55, 105.79) controlPoint2:CGPointMake(5.96, 88.58)];
            [fill5 addCurveToPoint:CGPointMake(69.56, 5.95) controlPoint1:CGPointMake(5.96, 34.34) controlPoint2:CGPointMake(34.43, 5.95)];
            CGContextSaveGState(context);
            CGContextTranslateCTM(context, 0.52, 0.39);
            fill5.usesEvenOddFillRule = YES;
            [UIColor.whiteColor setFill];
            [fill5 fill];
            CGContextRestoreGState(context);
            
            //! Fill 7
            UIBezierPath *fill7 = [UIBezierPath bezierPath];
            [fill7 moveToPoint:CGPointMake(27.09, 8.94)];
            [fill7 addCurveToPoint:CGPointMake(27.1, 8.78) controlPoint1:CGPointMake(27.09, 8.88) controlPoint2:CGPointMake(27.1, 8.83)];
            [fill7 addCurveToPoint:CGPointMake(22.81, 4.5) controlPoint1:CGPointMake(27.1, 6.42) controlPoint2:CGPointMake(25.18, 4.5)];
            [fill7 addCurveToPoint:CGPointMake(21.66, 4.66) controlPoint1:CGPointMake(22.41, 4.5) controlPoint2:CGPointMake(22.03, 4.56)];
            [fill7 addCurveToPoint:CGPointMake(16.71, 0) controlPoint1:CGPointMake(21.51, 2.06) controlPoint2:CGPointMake(19.36, 0)];
            [fill7 addCurveToPoint:CGPointMake(12.43, 2.45) controlPoint1:CGPointMake(14.89, 0) controlPoint2:CGPointMake(13.3, 0.98)];
            [fill7 addCurveToPoint:CGPointMake(9.48, 1.35) controlPoint1:CGPointMake(11.64, 1.77) controlPoint2:CGPointMake(10.61, 1.35)];
            [fill7 addCurveToPoint:CGPointMake(4.98, 5.63) controlPoint1:CGPointMake(7.07, 1.35) controlPoint2:CGPointMake(5.1, 3.25)];
            [fill7 addLineToPoint:CGPointMake(4.29, 5.63)];
            [fill7 addCurveToPoint:CGPointMake(0, 9.91) controlPoint1:CGPointMake(1.92, 5.63) controlPoint2:CGPointMake(0, 7.55)];
            [fill7 addCurveToPoint:CGPointMake(4.29, 14.19) controlPoint1:CGPointMake(0, 12.27) controlPoint2:CGPointMake(1.92, 14.19)];
            [fill7 addLineToPoint:CGPointMake(26.2, 14.19)];
            [fill7 addCurveToPoint:CGPointMake(28.91, 11.49) controlPoint1:CGPointMake(27.69, 14.19) controlPoint2:CGPointMake(28.91, 12.98)];
            [fill7 addCurveToPoint:CGPointMake(27.09, 8.94) controlPoint1:CGPointMake(28.91, 10.31) controlPoint2:CGPointMake(28.15, 9.31)];
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.1);
            CGContextBeginTransparencyLayer(context, nil);
            {
                CGContextTranslateCTM(context, 70.5, 22.14);
                fill7.usesEvenOddFillRule = YES;
                [UIColor.blackColor setFill];
                [fill7 fill];
            }
            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
            
            //! Fill 9
            UIBezierPath *fill9 = [UIBezierPath bezierPath];
            [fill9 moveToPoint:CGPointMake(16.52, 6.08)];
            [fill9 addCurveToPoint:CGPointMake(16.56, 5.56) controlPoint1:CGPointMake(16.55, 5.91) controlPoint2:CGPointMake(16.56, 5.74)];
            [fill9 addCurveToPoint:CGPointMake(13.35, 2.36) controlPoint1:CGPointMake(16.56, 3.79) controlPoint2:CGPointMake(15.13, 2.36)];
            [fill9 addCurveToPoint:CGPointMake(12.31, 2.54) controlPoint1:CGPointMake(12.99, 2.36) controlPoint2:CGPointMake(12.64, 2.42)];
            [fill9 addCurveToPoint:CGPointMake(8.11, 0) controlPoint1:CGPointMake(11.52, 1.03) controlPoint2:CGPointMake(9.94, 0)];
            [fill9 addCurveToPoint:CGPointMake(3.43, 4.06) controlPoint1:CGPointMake(5.72, 0) controlPoint2:CGPointMake(3.76, 1.77)];
            [fill9 addCurveToPoint:CGPointMake(0, 7.75) controlPoint1:CGPointMake(1.51, 4.21) controlPoint2:CGPointMake(0, 5.8)];
            [fill9 addCurveToPoint:CGPointMake(3.72, 11.46) controlPoint1:CGPointMake(0, 9.8) controlPoint2:CGPointMake(1.67, 11.46)];
            [fill9 addLineToPoint:CGPointMake(16.23, 11.46)];
            [fill9 addCurveToPoint:CGPointMake(18.93, 8.76) controlPoint1:CGPointMake(17.72, 11.46) controlPoint2:CGPointMake(18.93, 10.25)];
            [fill9 addCurveToPoint:CGPointMake(16.52, 6.08) controlPoint1:CGPointMake(18.93, 7.37) controlPoint2:CGPointMake(17.87, 6.23)];
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.1);
            CGContextBeginTransparencyLayer(context, nil);
            {
                CGContextTranslateCTM(context, 26.76, 36.6);
                fill9.usesEvenOddFillRule = YES;
                [UIColor.blackColor setFill];
                [fill9 fill];
            }
            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
            
            //! Car
            {
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 10.07, 51.36);
                
                //! Fill 11
                UIBezierPath *fill11 = [UIBezierPath bezierPath];
                [fill11 moveToPoint:CGPointMake(93.58, 2.41)];
                [fill11 addLineToPoint:CGPointMake(1.21, 2.41)];
                [fill11 addCurveToPoint:CGPointMake(0, 1.21) controlPoint1:CGPointMake(0.54, 2.41) controlPoint2:CGPointMake(0, 1.87)];
                [fill11 addCurveToPoint:CGPointMake(1.21, 0) controlPoint1:CGPointMake(0, 0.54) controlPoint2:CGPointMake(0.54, 0)];
                [fill11 addLineToPoint:CGPointMake(93.58, 0)];
                [fill11 addCurveToPoint:CGPointMake(94.79, 1.21) controlPoint1:CGPointMake(94.25, 0) controlPoint2:CGPointMake(94.79, 0.54)];
                [fill11 addCurveToPoint:CGPointMake(93.58, 2.41) controlPoint1:CGPointMake(94.79, 1.87) controlPoint2:CGPointMake(94.25, 2.41)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 27.46, 71.29);
                fill11.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill11 fill];
                CGContextRestoreGState(context);
                
                //! Fill 13
                UIBezierPath *fill13 = [UIBezierPath bezierPath];
                [fill13 moveToPoint:CGPointMake(54.53, 0)];
                [fill13 addCurveToPoint:CGPointMake(57.53, 2.1) controlPoint1:CGPointMake(55.57, 0) controlPoint2:CGPointMake(57.17, 1.12)];
                [fill13 addLineToPoint:CGPointMake(64.9, 22.29)];
                [fill13 addLineToPoint:CGPointMake(0, 22.29)];
                [fill13 addLineToPoint:CGPointMake(7.37, 2.1)];
                [fill13 addCurveToPoint:CGPointMake(10.37, 0) controlPoint1:CGPointMake(7.73, 1.12) controlPoint2:CGPointMake(9.33, 0)];
                [fill13 addLineToPoint:CGPointMake(54.53, 0)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 25.71, 8.41);
                fill13.usesEvenOddFillRule = YES;
                [UIColor.whiteColor setFill];
                [fill13 fill];
                CGContextRestoreGState(context);
                
                //! Fill 15
                UIBezierPath *fill15 = [UIBezierPath bezierPath];
                [fill15 moveToPoint:CGPointMake(2.94, 22.29)];
                [fill15 addLineToPoint:CGPointMake(64.38, 22.29)];
                [fill15 addLineToPoint:CGPointMake(57.6, 3.71)];
                [fill15 addCurveToPoint:CGPointMake(55.74, 2.41) controlPoint1:CGPointMake(57.42, 3.22) controlPoint2:CGPointMake(56.27, 2.41)];
                [fill15 addLineToPoint:CGPointMake(11.58, 2.41)];
                [fill15 addCurveToPoint:CGPointMake(9.72, 3.71) controlPoint1:CGPointMake(11.05, 2.41) controlPoint2:CGPointMake(9.9, 3.22)];
                [fill15 addLineToPoint:CGPointMake(2.94, 22.29)];
                [fill15 closePath];
                [fill15 moveToPoint:CGPointMake(66.11, 24.7)];
                [fill15 addLineToPoint:CGPointMake(1.21, 24.7)];
                [fill15 addCurveToPoint:CGPointMake(0.22, 24.18) controlPoint1:CGPointMake(0.82, 24.7) controlPoint2:CGPointMake(0.45, 24.51)];
                [fill15 addCurveToPoint:CGPointMake(0.07, 23.08) controlPoint1:CGPointMake(-0.01, 23.86) controlPoint2:CGPointMake(-0.06, 23.45)];
                [fill15 addLineToPoint:CGPointMake(7.44, 2.89)];
                [fill15 addCurveToPoint:CGPointMake(11.58, 0) controlPoint1:CGPointMake(7.97, 1.43) controlPoint2:CGPointMake(10.02, 0)];
                [fill15 addLineToPoint:CGPointMake(55.74, 0)];
                [fill15 addCurveToPoint:CGPointMake(59.88, 2.89) controlPoint1:CGPointMake(57.29, 0) controlPoint2:CGPointMake(59.34, 1.43)];
                [fill15 addLineToPoint:CGPointMake(67.25, 23.08)];
                [fill15 addCurveToPoint:CGPointMake(67.1, 24.18) controlPoint1:CGPointMake(67.38, 23.45) controlPoint2:CGPointMake(67.33, 23.86)];
                [fill15 addCurveToPoint:CGPointMake(66.11, 24.7) controlPoint1:CGPointMake(66.87, 24.51) controlPoint2:CGPointMake(66.5, 24.7)];
                [fill15 addLineToPoint:CGPointMake(66.11, 24.7)];
                [fill15 closePath];
                [fill15 moveToPoint:CGPointMake(66.11, 24.7)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 24.5, 7.2);
                fill15.usesEvenOddFillRule = YES;
                [[UIColor colorWithWhite:0.2 alpha:1] setFill];
                [fill15 fill];
                CGContextRestoreGState(context);
                
                //! Fill 17
                UIBezierPath *fill17 = [UIBezierPath bezierPath];
                [fill17 moveToPoint:CGPointMake(12.1, 0)];
                [fill17 addLineToPoint:CGPointMake(12.1, 12.92)];
                [fill17 addCurveToPoint:CGPointMake(6.05, 18.66) controlPoint1:CGPointMake(12.1, 16.09) controlPoint2:CGPointMake(9.39, 18.66)];
                [fill17 addCurveToPoint:CGPointMake(0, 12.92) controlPoint1:CGPointMake(2.71, 18.66) controlPoint2:CGPointMake(0, 16.09)];
                [fill17 addLineToPoint:CGPointMake(0, 3.35)];
                [fill17 addLineToPoint:CGPointMake(12.1, 0)];
                [fill17 closePath];
                [fill17 moveToPoint:CGPointMake(12.1, 0)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 22.32, 55.04);
                fill17.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill17 fill];
                CGContextRestoreGState(context);
                
                //! Fill 19
                UIBezierPath *fill19 = [UIBezierPath bezierPath];
                [fill19 moveToPoint:CGPointMake(12.1, 0)];
                [fill19 addLineToPoint:CGPointMake(12.1, 12.92)];
                [fill19 addCurveToPoint:CGPointMake(6.05, 18.66) controlPoint1:CGPointMake(12.1, 16.09) controlPoint2:CGPointMake(9.39, 18.66)];
                [fill19 addCurveToPoint:CGPointMake(0, 12.92) controlPoint1:CGPointMake(2.71, 18.66) controlPoint2:CGPointMake(0, 16.09)];
                [fill19 addLineToPoint:CGPointMake(0, 3.35)];
                [fill19 addLineToPoint:CGPointMake(12.1, 0)];
                [fill19 closePath];
                [fill19 moveToPoint:CGPointMake(12.1, 0)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 81.9, 55.04);
                fill19.usesEvenOddFillRule = YES;
                [UIColor.blackColor setFill];
                [fill19 fill];
                CGContextRestoreGState(context);
                
                //! Fill 21
                UIBezierPath *fill21 = [UIBezierPath bezierPath];
                [fill21 moveToPoint:CGPointMake(5.53, 35.56)];
                [fill21 addCurveToPoint:CGPointMake(0.87, 33.38) controlPoint1:CGPointMake(3.54, 35.56) controlPoint2:CGPointMake(1.85, 34.76)];
                [fill21 addCurveToPoint:CGPointMake(0.41, 28.27) controlPoint1:CGPointMake(-0.1, 31.99) controlPoint2:CGPointMake(-0.27, 30.13)];
                [fill21 addLineToPoint:CGPointMake(8.37, 6.46)];
                [fill21 addCurveToPoint:CGPointMake(17.63, 0) controlPoint1:CGPointMake(9.69, 2.84) controlPoint2:CGPointMake(13.76, 0)];
                [fill21 addLineToPoint:CGPointMake(61.78, 0)];
                [fill21 addCurveToPoint:CGPointMake(71.04, 6.46) controlPoint1:CGPointMake(65.65, 0) controlPoint2:CGPointMake(69.71, 2.84)];
                [fill21 addLineToPoint:CGPointMake(79, 28.27)];
                [fill21 addCurveToPoint:CGPointMake(78.54, 33.38) controlPoint1:CGPointMake(79.68, 30.13) controlPoint2:CGPointMake(79.51, 31.99)];
                [fill21 addCurveToPoint:CGPointMake(73.88, 35.56) controlPoint1:CGPointMake(77.56, 34.76) controlPoint2:CGPointMake(75.87, 35.56)];
                [fill21 addLineToPoint:CGPointMake(5.53, 35.56)];
                [fill21 closePath];
                [fill21 moveToPoint:CGPointMake(5.53, 35.56)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 18.45, 1.77);
                fill21.usesEvenOddFillRule = YES;
                [primaryColor setFill];
                [fill21 fill];
                CGContextRestoreGState(context);
                
                //! Fill 23
                UIBezierPath *fill23 = [UIBezierPath bezierPath];
                [fill23 moveToPoint:CGPointMake(62.99, 0)];
                [fill23 addLineToPoint:CGPointMake(18.84, 0)];
                [fill23 addCurveToPoint:CGPointMake(8.45, 7.26) controlPoint1:CGPointMake(14.49, 0) controlPoint2:CGPointMake(9.93, 3.19)];
                [fill23 addLineToPoint:CGPointMake(0.48, 29.06)];
                [fill23 addCurveToPoint:CGPointMake(1.09, 35.28) controlPoint1:CGPointMake(-0.33, 31.3) controlPoint2:CGPointMake(-0.11, 33.56)];
                [fill23 addCurveToPoint:CGPointMake(6.74, 37.97) controlPoint1:CGPointMake(2.29, 36.99) controlPoint2:CGPointMake(4.35, 37.97)];
                [fill23 addLineToPoint:CGPointMake(75.09, 37.97)];
                [fill23 addCurveToPoint:CGPointMake(80.74, 35.28) controlPoint1:CGPointMake(77.48, 37.97) controlPoint2:CGPointMake(79.54, 36.99)];
                [fill23 addCurveToPoint:CGPointMake(81.35, 29.06) controlPoint1:CGPointMake(81.94, 33.56) controlPoint2:CGPointMake(82.16, 31.3)];
                [fill23 addLineToPoint:CGPointMake(73.38, 7.26)];
                [fill23 addCurveToPoint:CGPointMake(62.99, 0) controlPoint1:CGPointMake(71.9, 3.19) controlPoint2:CGPointMake(67.34, 0)];
                [fill23 moveToPoint:CGPointMake(62.99, 2.41)];
                [fill23 addCurveToPoint:CGPointMake(71.11, 8.08) controlPoint1:CGPointMake(66.32, 2.41) controlPoint2:CGPointMake(69.97, 4.96)];
                [fill23 addLineToPoint:CGPointMake(79.07, 29.89)];
                [fill23 addCurveToPoint:CGPointMake(75.09, 35.56) controlPoint1:CGPointMake(80.21, 33.01) controlPoint2:CGPointMake(78.42, 35.56)];
                [fill23 addLineToPoint:CGPointMake(6.74, 35.56)];
                [fill23 addCurveToPoint:CGPointMake(2.76, 29.89) controlPoint1:CGPointMake(3.41, 35.56) controlPoint2:CGPointMake(1.62, 33.01)];
                [fill23 addLineToPoint:CGPointMake(10.72, 8.08)];
                [fill23 addCurveToPoint:CGPointMake(18.84, 2.41) controlPoint1:CGPointMake(11.86, 4.96) controlPoint2:CGPointMake(15.51, 2.41)];
                [fill23 addLineToPoint:CGPointMake(62.99, 2.41)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 17.24, 0.57);
                fill23.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill23 fill];
                CGContextRestoreGState(context);
                
                //! Fill 25
                UIBezierPath *fill2 = [UIBezierPath bezierPath];
                [fill2 moveToPoint:CGPointMake(54.53, 0)];
                [fill2 addCurveToPoint:CGPointMake(57.53, 2.1) controlPoint1:CGPointMake(55.57, 0) controlPoint2:CGPointMake(57.17, 1.12)];
                [fill2 addLineToPoint:CGPointMake(64.9, 22.29)];
                [fill2 addLineToPoint:CGPointMake(0, 22.29)];
                [fill2 addLineToPoint:CGPointMake(7.37, 2.1)];
                [fill2 addCurveToPoint:CGPointMake(10.37, 0) controlPoint1:CGPointMake(7.73, 1.12) controlPoint2:CGPointMake(9.33, 0)];
                [fill2 addLineToPoint:CGPointMake(54.53, 0)];
                CGContextSaveGState(context);
                CGContextSetAlpha(context, 0.45);
                CGContextBeginTransparencyLayer(context, nil);
                {
                    CGContextTranslateCTM(context, 25.71, 8.41);
                    fill2.usesEvenOddFillRule = YES;
                    [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                    [fill2 fill];
                }
                CGContextEndTransparencyLayer(context);
                CGContextRestoreGState(context);
                
                //! Fill 27
                UIBezierPath *fill27 = [UIBezierPath bezierPath];
                [fill27 moveToPoint:CGPointMake(2.94, 22.29)];
                [fill27 addLineToPoint:CGPointMake(64.38, 22.29)];
                [fill27 addLineToPoint:CGPointMake(57.6, 3.71)];
                [fill27 addCurveToPoint:CGPointMake(55.74, 2.41) controlPoint1:CGPointMake(57.42, 3.22) controlPoint2:CGPointMake(56.27, 2.41)];
                [fill27 addLineToPoint:CGPointMake(11.58, 2.41)];
                [fill27 addCurveToPoint:CGPointMake(9.72, 3.71) controlPoint1:CGPointMake(11.05, 2.41) controlPoint2:CGPointMake(9.9, 3.22)];
                [fill27 addLineToPoint:CGPointMake(2.94, 22.29)];
                [fill27 closePath];
                [fill27 moveToPoint:CGPointMake(66.11, 24.7)];
                [fill27 addLineToPoint:CGPointMake(1.21, 24.7)];
                [fill27 addCurveToPoint:CGPointMake(0.22, 24.18) controlPoint1:CGPointMake(0.82, 24.7) controlPoint2:CGPointMake(0.45, 24.51)];
                [fill27 addCurveToPoint:CGPointMake(0.07, 23.08) controlPoint1:CGPointMake(-0.01, 23.86) controlPoint2:CGPointMake(-0.06, 23.45)];
                [fill27 addLineToPoint:CGPointMake(7.44, 2.89)];
                [fill27 addCurveToPoint:CGPointMake(11.58, 0) controlPoint1:CGPointMake(7.97, 1.43) controlPoint2:CGPointMake(10.02, 0)];
                [fill27 addLineToPoint:CGPointMake(55.74, 0)];
                [fill27 addCurveToPoint:CGPointMake(59.88, 2.89) controlPoint1:CGPointMake(57.29, 0) controlPoint2:CGPointMake(59.34, 1.43)];
                [fill27 addLineToPoint:CGPointMake(67.25, 23.08)];
                [fill27 addCurveToPoint:CGPointMake(67.1, 24.18) controlPoint1:CGPointMake(67.38, 23.45) controlPoint2:CGPointMake(67.33, 23.86)];
                [fill27 addCurveToPoint:CGPointMake(66.11, 24.7) controlPoint1:CGPointMake(66.87, 24.51) controlPoint2:CGPointMake(66.5, 24.7)];
                [fill27 addLineToPoint:CGPointMake(66.11, 24.7)];
                [fill27 closePath];
                [fill27 moveToPoint:CGPointMake(66.11, 24.7)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 24.5, 7.2);
                fill27.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill27 fill];
                CGContextRestoreGState(context);
                
                //! Fill 29
                UIBezierPath *fill29 = [UIBezierPath bezierPath];
                [fill29 moveToPoint:CGPointMake(1.21, 22.6)];
                [fill29 addCurveToPoint:CGPointMake(0.8, 22.53) controlPoint1:CGPointMake(1.07, 22.6) controlPoint2:CGPointMake(0.93, 22.58)];
                [fill29 addCurveToPoint:CGPointMake(0.07, 20.98) controlPoint1:CGPointMake(0.17, 22.3) controlPoint2:CGPointMake(-0.16, 21.61)];
                [fill29 addLineToPoint:CGPointMake(7.44, 0.79)];
                [fill29 addCurveToPoint:CGPointMake(8.99, 0.07) controlPoint1:CGPointMake(7.67, 0.17) controlPoint2:CGPointMake(8.36, -0.15)];
                [fill29 addCurveToPoint:CGPointMake(9.72, 1.62) controlPoint1:CGPointMake(9.62, 0.3) controlPoint2:CGPointMake(9.95, 0.99)];
                [fill29 addLineToPoint:CGPointMake(2.35, 21.81)];
                [fill29 addCurveToPoint:CGPointMake(1.21, 22.6) controlPoint1:CGPointMake(2.17, 22.3) controlPoint2:CGPointMake(1.7, 22.6)];
                CGContextSaveGState(context);
                CGContextSetAlpha(context, 0.2);
                CGContextBeginTransparencyLayer(context, nil);
                {
                    CGContextTranslateCTM(context, 28.77, 11.85);
                    fill29.usesEvenOddFillRule = YES;
                    [UIColor.whiteColor setFill];
                    [fill29 fill];
                }
                CGContextEndTransparencyLayer(context);
                CGContextRestoreGState(context);
                
                //! Fill 31
                UIBezierPath *fill31 = [UIBezierPath bezierPath];
                [fill31 moveToPoint:CGPointMake(1.21, 10.24)];
                [fill31 addCurveToPoint:CGPointMake(0.15, 9.62) controlPoint1:CGPointMake(0.79, 10.24) controlPoint2:CGPointMake(0.37, 10.02)];
                [fill31 addCurveToPoint:CGPointMake(0.62, 7.98) controlPoint1:CGPointMake(-0.17, 9.04) controlPoint2:CGPointMake(0.04, 8.31)];
                [fill31 addLineToPoint:CGPointMake(14.7, 0.15)];
                [fill31 addCurveToPoint:CGPointMake(16.35, 0.62) controlPoint1:CGPointMake(15.28, -0.17) controlPoint2:CGPointMake(16.02, 0.04)];
                [fill31 addCurveToPoint:CGPointMake(15.88, 2.26) controlPoint1:CGPointMake(16.67, 1.2) controlPoint2:CGPointMake(16.46, 1.94)];
                [fill31 addLineToPoint:CGPointMake(1.8, 10.09)];
                [fill31 addCurveToPoint:CGPointMake(1.21, 10.24) controlPoint1:CGPointMake(1.61, 10.19) controlPoint2:CGPointMake(1.41, 10.24)];
                CGContextSaveGState(context);
                CGContextSetAlpha(context, 0.2);
                CGContextBeginTransparencyLayer(context, nil);
                {
                    CGContextTranslateCTM(context, 67.68, 11.33);
                    fill31.usesEvenOddFillRule = YES;
                    [UIColor.blackColor setFill];
                    [fill31 fill];
                }
                CGContextEndTransparencyLayer(context);
                CGContextRestoreGState(context);
                
                //! Fill 33
                UIBezierPath *fill33 = [UIBezierPath bezierPath];
                [fill33 moveToPoint:CGPointMake(1.21, 8)];
                [fill33 addCurveToPoint:CGPointMake(0.15, 7.38) controlPoint1:CGPointMake(0.79, 8) controlPoint2:CGPointMake(0.37, 7.78)];
                [fill33 addCurveToPoint:CGPointMake(0.62, 5.74) controlPoint1:CGPointMake(-0.17, 6.8) controlPoint2:CGPointMake(0.04, 6.07)];
                [fill33 addLineToPoint:CGPointMake(10.67, 0.15)];
                [fill33 addCurveToPoint:CGPointMake(12.32, 0.62) controlPoint1:CGPointMake(11.25, -0.17) controlPoint2:CGPointMake(11.99, 0.04)];
                [fill33 addCurveToPoint:CGPointMake(11.85, 2.26) controlPoint1:CGPointMake(12.64, 1.2) controlPoint2:CGPointMake(12.43, 1.94)];
                [fill33 addLineToPoint:CGPointMake(1.8, 7.85)];
                [fill33 addCurveToPoint:CGPointMake(1.21, 8) controlPoint1:CGPointMake(1.61, 7.95) controlPoint2:CGPointMake(1.41, 8)];
                CGContextSaveGState(context);
                CGContextSetAlpha(context, 0.2);
                CGContextBeginTransparencyLayer(context, nil);
                {
                    CGContextTranslateCTM(context, 73.73, 15.98);
                    fill33.usesEvenOddFillRule = YES;
                    [UIColor.blackColor setFill];
                    [fill33 fill];
                }
                CGContextEndTransparencyLayer(context);
                CGContextRestoreGState(context);
                
                //! Fill 35
                UIBezierPath *fill35 = [UIBezierPath bezierPath];
                [fill35 moveToPoint:CGPointMake(5.93, 3.3)];
                [fill35 addLineToPoint:CGPointZero];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 13.78, 25.03);
                fill35.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.012 saturation:0.922 brightness:1 alpha:1] setFill];
                [fill35 fill];
                CGContextRestoreGState(context);
                
                //! Fill 37
                UIBezierPath *fill37 = [UIBezierPath bezierPath];
                [fill37 moveToPoint:CGPointMake(7.14, 5.71)];
                [fill37 addCurveToPoint:CGPointMake(6.56, 5.56) controlPoint1:CGPointMake(6.94, 5.71) controlPoint2:CGPointMake(6.74, 5.66)];
                [fill37 addLineToPoint:CGPointMake(0.62, 2.26)];
                [fill37 addCurveToPoint:CGPointMake(0.15, 0.62) controlPoint1:CGPointMake(0.04, 1.94) controlPoint2:CGPointMake(-0.17, 1.2)];
                [fill37 addCurveToPoint:CGPointMake(1.8, 0.15) controlPoint1:CGPointMake(0.48, 0.04) controlPoint2:CGPointMake(1.22, -0.17)];
                [fill37 addLineToPoint:CGPointMake(7.73, 3.45)];
                [fill37 addCurveToPoint:CGPointMake(8.2, 5.09) controlPoint1:CGPointMake(8.32, 3.78) controlPoint2:CGPointMake(8.53, 4.51)];
                [fill37 addCurveToPoint:CGPointMake(7.14, 5.71) controlPoint1:CGPointMake(7.98, 5.49) controlPoint2:CGPointMake(7.57, 5.71)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 12.57, 23.82);
                fill37.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill37 fill];
                CGContextRestoreGState(context);
                
                //! Fill 39
                UIBezierPath *fill39 = [UIBezierPath bezierPath];
                [fill39 moveToPoint:CGPointMake(4.42, 9.65)];
                [fill39 addCurveToPoint:CGPointMake(0, 4.83) controlPoint1:CGPointMake(1.98, 9.65) controlPoint2:CGPointMake(0, 7.49)];
                [fill39 addCurveToPoint:CGPointMake(4.42, 0) controlPoint1:CGPointMake(0, 2.16) controlPoint2:CGPointMake(1.98, 0)];
                [fill39 addLineToPoint:CGPointMake(8.44, 0)];
                [fill39 addCurveToPoint:CGPointMake(12.85, 4.83) controlPoint1:CGPointMake(10.87, 0) controlPoint2:CGPointMake(12.85, 2.16)];
                [fill39 addCurveToPoint:CGPointMake(8.44, 9.65) controlPoint1:CGPointMake(12.85, 7.49) controlPoint2:CGPointMake(10.87, 9.65)];
                [fill39 addLineToPoint:CGPointMake(4.42, 9.65)];
                [fill39 closePath];
                [fill39 moveToPoint:CGPointMake(4.42, 9.65)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 2.13, 17.64);
                fill39.usesEvenOddFillRule = YES;
                [primaryColor setFill];
                [fill39 fill];
                CGContextRestoreGState(context);
                
                //! Fill 41
                UIBezierPath *fill41 = [UIBezierPath bezierPath];
                [fill41 moveToPoint:CGPointMake(9.65, 0)];
                [fill41 addLineToPoint:CGPointMake(5.63, 0)];
                [fill41 addCurveToPoint:CGPointMake(0, 6.03) controlPoint1:CGPointMake(2.52, 0) controlPoint2:CGPointMake(0, 2.71)];
                [fill41 addCurveToPoint:CGPointMake(5.63, 12.06) controlPoint1:CGPointMake(0, 9.36) controlPoint2:CGPointMake(2.52, 12.06)];
                [fill41 addLineToPoint:CGPointMake(9.65, 12.06)];
                [fill41 addCurveToPoint:CGPointMake(15.27, 6.03) controlPoint1:CGPointMake(12.75, 12.06) controlPoint2:CGPointMake(15.27, 9.36)];
                [fill41 addCurveToPoint:CGPointMake(9.65, 0) controlPoint1:CGPointMake(15.27, 2.71) controlPoint2:CGPointMake(12.75, 0)];
                [fill41 moveToPoint:CGPointMake(9.65, 2.41)];
                [fill41 addCurveToPoint:CGPointMake(12.85, 6.03) controlPoint1:CGPointMake(11.42, 2.41) controlPoint2:CGPointMake(12.85, 4.03)];
                [fill41 addCurveToPoint:CGPointMake(9.65, 9.65) controlPoint1:CGPointMake(12.85, 8.03) controlPoint2:CGPointMake(11.42, 9.65)];
                [fill41 addLineToPoint:CGPointMake(5.63, 9.65)];
                [fill41 addCurveToPoint:CGPointMake(2.42, 6.03) controlPoint1:CGPointMake(3.86, 9.65) controlPoint2:CGPointMake(2.42, 8.03)];
                [fill41 addCurveToPoint:CGPointMake(5.63, 2.41) controlPoint1:CGPointMake(2.42, 4.03) controlPoint2:CGPointMake(3.86, 2.41)];
                [fill41 addLineToPoint:CGPointMake(9.65, 2.41)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 0.92, 16.43);
                fill41.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill41 fill];
                CGContextRestoreGState(context);
                
                //! Fill 43
                UIBezierPath *fill43 = [UIBezierPath bezierPath];
                [fill43 moveToPoint:CGPointMake(0, 3.3)];
                [fill43 addLineToPoint:CGPointMake(5.93, 0)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 96.6, 25.03);
                fill43.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill43 fill];
                CGContextRestoreGState(context);
                
                //! Fill 45
                UIBezierPath *fill45 = [UIBezierPath bezierPath];
                [fill45 moveToPoint:CGPointMake(1.21, 5.71)];
                [fill45 addCurveToPoint:CGPointMake(0.15, 5.09) controlPoint1:CGPointMake(0.79, 5.71) controlPoint2:CGPointMake(0.37, 5.49)];
                [fill45 addCurveToPoint:CGPointMake(0.62, 3.45) controlPoint1:CGPointMake(-0.17, 4.51) controlPoint2:CGPointMake(0.04, 3.78)];
                [fill45 addLineToPoint:CGPointMake(6.55, 0.15)];
                [fill45 addCurveToPoint:CGPointMake(8.2, 0.62) controlPoint1:CGPointMake(7.14, -0.17) controlPoint2:CGPointMake(7.88, 0.04)];
                [fill45 addCurveToPoint:CGPointMake(7.73, 2.26) controlPoint1:CGPointMake(8.53, 1.2) controlPoint2:CGPointMake(8.32, 1.94)];
                [fill45 addLineToPoint:CGPointMake(1.8, 5.56)];
                [fill45 addCurveToPoint:CGPointMake(1.21, 5.71) controlPoint1:CGPointMake(1.61, 5.66) controlPoint2:CGPointMake(1.41, 5.71)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 95.39, 23.82);
                fill45.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill45 fill];
                CGContextRestoreGState(context);
                
                //! Fill 47
                UIBezierPath *fill47 = [UIBezierPath bezierPath];
                [fill47 moveToPoint:CGPointMake(4.42, 9.65)];
                [fill47 addCurveToPoint:CGPointMake(0, 4.83) controlPoint1:CGPointMake(1.98, 9.65) controlPoint2:CGPointMake(0, 7.49)];
                [fill47 addCurveToPoint:CGPointMake(4.42, 0) controlPoint1:CGPointMake(0, 2.16) controlPoint2:CGPointMake(1.98, 0)];
                [fill47 addLineToPoint:CGPointMake(8.44, 0)];
                [fill47 addCurveToPoint:CGPointMake(12.85, 4.83) controlPoint1:CGPointMake(10.87, 0) controlPoint2:CGPointMake(12.85, 2.16)];
                [fill47 addCurveToPoint:CGPointMake(8.44, 9.65) controlPoint1:CGPointMake(12.85, 7.49) controlPoint2:CGPointMake(10.87, 9.65)];
                [fill47 addLineToPoint:CGPointMake(4.42, 9.65)];
                [fill47 closePath];
                [fill47 moveToPoint:CGPointMake(4.42, 9.65)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 101.33, 17.64);
                fill47.usesEvenOddFillRule = YES;
                [primaryColor setFill];
                [fill47 fill];
                CGContextRestoreGState(context);
                
                //! Fill 49
                UIBezierPath *fill49 = [UIBezierPath bezierPath];
                [fill49 moveToPoint:CGPointMake(9.65, 0)];
                [fill49 addLineToPoint:CGPointMake(5.63, 0)];
                [fill49 addCurveToPoint:CGPointMake(0, 6.03) controlPoint1:CGPointMake(2.53, 0) controlPoint2:CGPointMake(0, 2.71)];
                [fill49 addCurveToPoint:CGPointMake(5.63, 12.06) controlPoint1:CGPointMake(0, 9.36) controlPoint2:CGPointMake(2.53, 12.06)];
                [fill49 addLineToPoint:CGPointMake(9.65, 12.06)];
                [fill49 addCurveToPoint:CGPointMake(15.27, 6.03) controlPoint1:CGPointMake(12.75, 12.06) controlPoint2:CGPointMake(15.27, 9.36)];
                [fill49 addCurveToPoint:CGPointMake(9.65, 0) controlPoint1:CGPointMake(15.27, 2.71) controlPoint2:CGPointMake(12.75, 0)];
                [fill49 moveToPoint:CGPointMake(9.65, 2.41)];
                [fill49 addCurveToPoint:CGPointMake(12.85, 6.03) controlPoint1:CGPointMake(11.42, 2.41) controlPoint2:CGPointMake(12.85, 4.03)];
                [fill49 addCurveToPoint:CGPointMake(9.65, 9.65) controlPoint1:CGPointMake(12.85, 8.03) controlPoint2:CGPointMake(11.42, 9.65)];
                [fill49 addLineToPoint:CGPointMake(5.63, 9.65)];
                [fill49 addCurveToPoint:CGPointMake(2.42, 6.03) controlPoint1:CGPointMake(3.86, 9.65) controlPoint2:CGPointMake(2.42, 8.03)];
                [fill49 addCurveToPoint:CGPointMake(5.63, 2.41) controlPoint1:CGPointMake(2.42, 4.03) controlPoint2:CGPointMake(3.86, 2.41)];
                [fill49 addLineToPoint:CGPointMake(9.65, 2.41)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 100.12, 16.43);
                fill49.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill49 fill];
                CGContextRestoreGState(context);
                
                //! Fill 51
                UIBezierPath *fill51 = [UIBezierPath bezierPath];
                [fill51 moveToPoint:CGPointMake(2.94, 22.29)];
                [fill51 addLineToPoint:CGPointMake(64.38, 22.29)];
                [fill51 addLineToPoint:CGPointMake(57.6, 3.71)];
                [fill51 addCurveToPoint:CGPointMake(55.74, 2.41) controlPoint1:CGPointMake(57.42, 3.22) controlPoint2:CGPointMake(56.27, 2.41)];
                [fill51 addLineToPoint:CGPointMake(11.58, 2.41)];
                [fill51 addCurveToPoint:CGPointMake(9.72, 3.71) controlPoint1:CGPointMake(11.05, 2.41) controlPoint2:CGPointMake(9.9, 3.22)];
                [fill51 addLineToPoint:CGPointMake(2.94, 22.29)];
                [fill51 closePath];
                [fill51 moveToPoint:CGPointMake(66.11, 24.7)];
                [fill51 addLineToPoint:CGPointMake(1.21, 24.7)];
                [fill51 addCurveToPoint:CGPointMake(0.22, 24.18) controlPoint1:CGPointMake(0.82, 24.7) controlPoint2:CGPointMake(0.45, 24.51)];
                [fill51 addCurveToPoint:CGPointMake(0.07, 23.08) controlPoint1:CGPointMake(-0.01, 23.86) controlPoint2:CGPointMake(-0.06, 23.45)];
                [fill51 addLineToPoint:CGPointMake(7.44, 2.89)];
                [fill51 addCurveToPoint:CGPointMake(11.58, 0) controlPoint1:CGPointMake(7.97, 1.43) controlPoint2:CGPointMake(10.02, 0)];
                [fill51 addLineToPoint:CGPointMake(55.74, 0)];
                [fill51 addCurveToPoint:CGPointMake(59.88, 2.89) controlPoint1:CGPointMake(57.29, 0) controlPoint2:CGPointMake(59.34, 1.43)];
                [fill51 addLineToPoint:CGPointMake(67.25, 23.08)];
                [fill51 addCurveToPoint:CGPointMake(67.1, 24.18) controlPoint1:CGPointMake(67.38, 23.45) controlPoint2:CGPointMake(67.33, 23.86)];
                [fill51 addCurveToPoint:CGPointMake(66.11, 24.7) controlPoint1:CGPointMake(66.87, 24.51) controlPoint2:CGPointMake(66.5, 24.7)];
                [fill51 addLineToPoint:CGPointMake(66.11, 24.7)];
                [fill51 closePath];
                [fill51 moveToPoint:CGPointMake(66.11, 24.7)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 24.5, 7.2);
                fill51.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill51 fill];
                CGContextRestoreGState(context);
                
                //! Fill 53
                UIBezierPath *fill53 = [UIBezierPath bezierPath];
                [fill53 moveToPoint:CGPointMake(7.26, 32.57)];
                [fill53 addCurveToPoint:CGPointMake(0, 25.33) controlPoint1:CGPointMake(3.26, 32.57) controlPoint2:CGPointMake(0, 29.33)];
                [fill53 addLineToPoint:CGPointMake(0, 7.24)];
                [fill53 addCurveToPoint:CGPointMake(7.26, 0) controlPoint1:CGPointMake(0, 3.25) controlPoint2:CGPointMake(3.26, 0)];
                [fill53 addLineToPoint:CGPointMake(87.1, 0)];
                [fill53 addCurveToPoint:CGPointMake(94.36, 7.24) controlPoint1:CGPointMake(91.11, 0) controlPoint2:CGPointMake(94.36, 3.25)];
                [fill53 addLineToPoint:CGPointMake(94.36, 25.33)];
                [fill53 addCurveToPoint:CGPointMake(87.1, 32.57) controlPoint1:CGPointMake(94.36, 29.33) controlPoint2:CGPointMake(91.11, 32.57)];
                [fill53 addLineToPoint:CGPointMake(7.26, 32.57)];
                [fill53 closePath];
                [fill53 moveToPoint:CGPointMake(7.26, 32.57)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 10.98, 29.1);
                fill53.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.012 saturation:0.461 brightness:1 alpha:1] setFill];
                [fill53 fill];
                CGContextRestoreGState(context);
                
                //! Fill 55
                UIBezierPath *fill55 = [UIBezierPath bezierPath];
                [fill55 moveToPoint:CGPointMake(88.31, 0)];
                [fill55 addLineToPoint:CGPointMake(8.47, 0)];
                [fill55 addCurveToPoint:CGPointMake(0, 8.44) controlPoint1:CGPointMake(3.8, 0) controlPoint2:CGPointMake(0, 3.79)];
                [fill55 addLineToPoint:CGPointMake(0, 26.54)];
                [fill55 addCurveToPoint:CGPointMake(8.47, 34.98) controlPoint1:CGPointMake(0, 31.2) controlPoint2:CGPointMake(3.8, 34.98)];
                [fill55 addLineToPoint:CGPointMake(88.31, 34.98)];
                [fill55 addCurveToPoint:CGPointMake(96.78, 26.54) controlPoint1:CGPointMake(92.98, 34.98) controlPoint2:CGPointMake(96.78, 31.2)];
                [fill55 addLineToPoint:CGPointMake(96.78, 8.44)];
                [fill55 addCurveToPoint:CGPointMake(88.31, 0) controlPoint1:CGPointMake(96.78, 3.79) controlPoint2:CGPointMake(92.98, 0)];
                [fill55 moveToPoint:CGPointMake(88.31, 2.41)];
                [fill55 addCurveToPoint:CGPointMake(94.36, 8.44) controlPoint1:CGPointMake(91.64, 2.41) controlPoint2:CGPointMake(94.36, 5.13)];
                [fill55 addLineToPoint:CGPointMake(94.36, 26.54)];
                [fill55 addCurveToPoint:CGPointMake(88.31, 32.57) controlPoint1:CGPointMake(94.36, 29.86) controlPoint2:CGPointMake(91.64, 32.57)];
                [fill55 addLineToPoint:CGPointMake(8.47, 32.57)];
                [fill55 addCurveToPoint:CGPointMake(2.42, 26.54) controlPoint1:CGPointMake(5.14, 32.57) controlPoint2:CGPointMake(2.42, 29.86)];
                [fill55 addLineToPoint:CGPointMake(2.42, 8.44)];
                [fill55 addCurveToPoint:CGPointMake(8.47, 2.41) controlPoint1:CGPointMake(2.42, 5.13) controlPoint2:CGPointMake(5.14, 2.41)];
                [fill55 addLineToPoint:CGPointMake(88.31, 2.41)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 9.77, 27.89);
                fill55.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill55 fill];
                CGContextRestoreGState(context);
                
                //! Bonnet
                UIBezierPath *bonnet = [UIBezierPath bezierPath];
                [bonnet moveToPoint:CGPointMake(91.94, 24.13)];
                [bonnet addCurveToPoint:CGPointMake(85.89, 30.16) controlPoint1:CGPointMake(91.94, 27.45) controlPoint2:CGPointMake(89.22, 30.16)];
                [bonnet addLineToPoint:CGPointMake(6.05, 30.16)];
                [bonnet addCurveToPoint:CGPointMake(0, 24.13) controlPoint1:CGPointMake(2.72, 30.16) controlPoint2:CGPointMake(0, 27.45)];
                [bonnet addLineToPoint:CGPointMake(0, 6.03)];
                [bonnet addCurveToPoint:CGPointMake(6.05, 0) controlPoint1:CGPointMake(0, 2.71) controlPoint2:CGPointMake(2.72, 0)];
                [bonnet addLineToPoint:CGPointMake(85.89, 0)];
                [bonnet addCurveToPoint:CGPointMake(91.94, 6.03) controlPoint1:CGPointMake(89.22, 0) controlPoint2:CGPointMake(91.94, 2.71)];
                [bonnet addLineToPoint:CGPointMake(91.94, 24.13)];
                [bonnet closePath];
                [bonnet moveToPoint:CGPointMake(91.94, 24.13)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 12.18, 30.3);
                bonnet.usesEvenOddFillRule = YES;
                [primaryColor setFill];
                [bonnet fill];
                CGContextRestoreGState(context);
                
                //! Fill 59
                UIBezierPath *fill59 = [UIBezierPath bezierPath];
                [fill59 moveToPoint:CGPointMake(4.84, 9.65)];
                [fill59 addCurveToPoint:CGPointMake(0, 4.83) controlPoint1:CGPointMake(2.17, 9.65) controlPoint2:CGPointMake(0, 7.49)];
                [fill59 addCurveToPoint:CGPointMake(4.84, 0) controlPoint1:CGPointMake(0, 2.16) controlPoint2:CGPointMake(2.17, 0)];
                [fill59 addCurveToPoint:CGPointMake(9.68, 4.83) controlPoint1:CGPointMake(7.51, 0) controlPoint2:CGPointMake(9.68, 2.16)];
                [fill59 addCurveToPoint:CGPointMake(4.84, 9.65) controlPoint1:CGPointMake(9.68, 7.49) controlPoint2:CGPointMake(7.51, 9.65)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 21.71, 40.56);
                fill59.usesEvenOddFillRule = YES;
                [[UIColor colorWithWhite:0.89 alpha:1] setFill];
                [fill59 fill];
                CGContextRestoreGState(context);
                
                //! Fill 61
                UIBezierPath *fill61 = [UIBezierPath bezierPath];
                [fill61 moveToPoint:CGPointMake(0, 4.83)];
                [fill61 addCurveToPoint:CGPointMake(4.84, 0) controlPoint1:CGPointMake(0, 2.16) controlPoint2:CGPointMake(2.17, 0)];
                [fill61 addCurveToPoint:CGPointMake(9.68, 4.83) controlPoint1:CGPointMake(7.51, 0) controlPoint2:CGPointMake(9.68, 2.16)];
                [fill61 addCurveToPoint:CGPointMake(4.84, 9.65) controlPoint1:CGPointMake(9.68, 7.49) controlPoint2:CGPointMake(7.51, 9.65)];
                [fill61 addCurveToPoint:CGPointMake(0, 4.83) controlPoint1:CGPointMake(2.17, 9.65) controlPoint2:CGPointMake(0, 7.49)];
                [fill61 closePath];
                [fill61 moveToPoint:CGPointMake(0, 4.83)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 84.92, 40.56);
                fill61.usesEvenOddFillRule = YES;
                [[UIColor colorWithWhite:0.89 alpha:1] setFill];
                [fill61 fill];
                CGContextRestoreGState(context);
                
                //! Fill 63
                UIBezierPath *fill63 = [UIBezierPath bezierPath];
                [fill63 moveToPoint:CGPointMake(37.5, 2.41)];
                [fill63 addLineToPoint:CGPointMake(1.21, 2.41)];
                [fill63 addCurveToPoint:CGPointMake(0, 1.21) controlPoint1:CGPointMake(0.54, 2.41) controlPoint2:CGPointMake(0, 1.87)];
                [fill63 addCurveToPoint:CGPointMake(1.21, 0) controlPoint1:CGPointMake(0, 0.54) controlPoint2:CGPointMake(0.54, 0)];
                [fill63 addLineToPoint:CGPointMake(37.5, 0)];
                [fill63 addCurveToPoint:CGPointMake(38.71, 1.21) controlPoint1:CGPointMake(38.17, 0) controlPoint2:CGPointMake(38.71, 0.54)];
                [fill63 addCurveToPoint:CGPointMake(37.5, 2.41) controlPoint1:CGPointMake(38.71, 1.87) controlPoint2:CGPointMake(38.17, 2.41)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 38.8, 44.18);
                fill63.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill63 fill];
                CGContextRestoreGState(context);
                
                //! Fill 65
                UIBezierPath *fill65 = [UIBezierPath bezierPath];
                [fill65 moveToPoint:CGPointMake(71.69, 2.41)];
                [fill65 addLineToPoint:CGPointMake(1.21, 2.41)];
                [fill65 addCurveToPoint:CGPointMake(0, 1.21) controlPoint1:CGPointMake(0.54, 2.41) controlPoint2:CGPointMake(0, 1.87)];
                [fill65 addCurveToPoint:CGPointMake(1.21, 0) controlPoint1:CGPointMake(0, 0.54) controlPoint2:CGPointMake(0.54, 0)];
                [fill65 addLineToPoint:CGPointMake(71.69, 0)];
                [fill65 addCurveToPoint:CGPointMake(72.9, 1.21) controlPoint1:CGPointMake(72.36, 0) controlPoint2:CGPointMake(72.9, 0.54)];
                [fill65 addCurveToPoint:CGPointMake(71.69, 2.41) controlPoint1:CGPointMake(72.9, 1.87) controlPoint2:CGPointMake(72.36, 2.41)];
                CGContextSaveGState(context);
                CGContextSetAlpha(context, 0.2);
                CGContextBeginTransparencyLayer(context, nil);
                {
                    CGContextTranslateCTM(context, 21.71, 32.25);
                    fill65.usesEvenOddFillRule = YES;
                    [UIColor.whiteColor setFill];
                    [fill65 fill];
                }
                CGContextEndTransparencyLayer(context);
                CGContextRestoreGState(context);
                
                //! Fill 67
                UIBezierPath *fill67 = [UIBezierPath bezierPath];
                [fill67 moveToPoint:CGPointMake(80.23, 2.41)];
                [fill67 addLineToPoint:CGPointMake(1.21, 2.41)];
                [fill67 addCurveToPoint:CGPointMake(0, 1.21) controlPoint1:CGPointMake(0.54, 2.41) controlPoint2:CGPointMake(0, 1.87)];
                [fill67 addCurveToPoint:CGPointMake(1.21, 0) controlPoint1:CGPointMake(0, 0.54) controlPoint2:CGPointMake(0.54, 0)];
                [fill67 addLineToPoint:CGPointMake(80.23, 0)];
                [fill67 addCurveToPoint:CGPointMake(81.44, 1.21) controlPoint1:CGPointMake(80.9, 0) controlPoint2:CGPointMake(81.44, 0.54)];
                [fill67 addCurveToPoint:CGPointMake(80.23, 2.41) controlPoint1:CGPointMake(81.44, 1.87) controlPoint2:CGPointMake(80.9, 2.41)];
                CGContextSaveGState(context);
                CGContextSetAlpha(context, 0.1);
                CGContextBeginTransparencyLayer(context, nil);
                {
                    CGContextTranslateCTM(context, 17.44, 56.23);
                    fill67.usesEvenOddFillRule = YES;
                    [UIColor.blackColor setFill];
                    [fill67 fill];
                }
                CGContextEndTransparencyLayer(context);
                CGContextRestoreGState(context);
                
                //! Stroke 69
                UIBezierPath *stroke69 = [UIBezierPath bezierPath];
                [stroke69 moveToPoint:CGPointMake(0, 3.62)];
                [stroke69 addCurveToPoint:CGPointMake(3.63, 0) controlPoint1:CGPointMake(0, 1.62) controlPoint2:CGPointMake(1.62, 0)];
                CGContextSaveGState(context);
                CGContextSetAlpha(context, 0.2);
                CGContextBeginTransparencyLayer(context, nil);
                {
                    CGContextTranslateCTM(context, 22.92, 41.77);
                    stroke69.lineJoinStyle = kCGLineJoinRound;
                    stroke69.lineCapStyle = kCGLineCapRound;
                    stroke69.lineWidth = 3;
                    [UIColor.whiteColor setStroke];
                    [stroke69 stroke];
                }
                CGContextEndTransparencyLayer(context);
                CGContextRestoreGState(context);
                
                //! Fill 71
                UIBezierPath *fill71 = [UIBezierPath bezierPath];
                [fill71 moveToPoint:CGPointMake(6.05, 0)];
                [fill71 addCurveToPoint:CGPointMake(0, 6.03) controlPoint1:CGPointMake(2.71, 0) controlPoint2:CGPointMake(0, 2.71)];
                [fill71 addCurveToPoint:CGPointMake(6.05, 12.06) controlPoint1:CGPointMake(0, 9.36) controlPoint2:CGPointMake(2.71, 12.06)];
                [fill71 addCurveToPoint:CGPointMake(12.1, 6.03) controlPoint1:CGPointMake(9.38, 12.06) controlPoint2:CGPointMake(12.1, 9.36)];
                [fill71 addCurveToPoint:CGPointMake(6.05, 0) controlPoint1:CGPointMake(12.1, 2.71) controlPoint2:CGPointMake(9.38, 0)];
                [fill71 moveToPoint:CGPointMake(6.05, 2.41)];
                [fill71 addCurveToPoint:CGPointMake(9.68, 6.03) controlPoint1:CGPointMake(8.05, 2.41) controlPoint2:CGPointMake(9.68, 4.03)];
                [fill71 addCurveToPoint:CGPointMake(6.05, 9.65) controlPoint1:CGPointMake(9.68, 8.03) controlPoint2:CGPointMake(8.05, 9.65)];
                [fill71 addCurveToPoint:CGPointMake(2.42, 6.03) controlPoint1:CGPointMake(4.04, 9.65) controlPoint2:CGPointMake(2.42, 8.03)];
                [fill71 addCurveToPoint:CGPointMake(6.05, 2.41) controlPoint1:CGPointMake(2.42, 4.03) controlPoint2:CGPointMake(4.04, 2.41)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 20.5, 39.35);
                fill71.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill71 fill];
                CGContextRestoreGState(context);
                
                //! Stroke 73
                UIBezierPath *stroke73 = [UIBezierPath bezierPath];
                [stroke73 moveToPoint:CGPointMake(0, 3.62)];
                [stroke73 addCurveToPoint:CGPointMake(3.63, 0) controlPoint1:CGPointMake(0, 1.62) controlPoint2:CGPointMake(1.62, 0)];
                CGContextSaveGState(context);
                CGContextSetAlpha(context, 0.2);
                CGContextBeginTransparencyLayer(context, nil);
                {
                    CGContextTranslateCTM(context, 86.13, 41.77);
                    stroke73.lineJoinStyle = kCGLineJoinRound;
                    stroke73.lineCapStyle = kCGLineCapRound;
                    stroke73.lineWidth = 3;
                    [UIColor.whiteColor setStroke];
                    [stroke73 stroke];
                }
                CGContextEndTransparencyLayer(context);
                CGContextRestoreGState(context);
                
                //! Fill 75
                UIBezierPath *fill75 = [UIBezierPath bezierPath];
                [fill75 moveToPoint:CGPointMake(6.05, 0)];
                [fill75 addCurveToPoint:CGPointMake(0, 6.03) controlPoint1:CGPointMake(2.71, 0) controlPoint2:CGPointMake(0, 2.71)];
                [fill75 addCurveToPoint:CGPointMake(6.05, 12.06) controlPoint1:CGPointMake(0, 9.36) controlPoint2:CGPointMake(2.71, 12.06)];
                [fill75 addCurveToPoint:CGPointMake(12.1, 6.03) controlPoint1:CGPointMake(9.38, 12.06) controlPoint2:CGPointMake(12.1, 9.36)];
                [fill75 addCurveToPoint:CGPointMake(6.05, 0) controlPoint1:CGPointMake(12.1, 2.71) controlPoint2:CGPointMake(9.38, 0)];
                [fill75 moveToPoint:CGPointMake(6.05, 2.41)];
                [fill75 addCurveToPoint:CGPointMake(9.68, 6.03) controlPoint1:CGPointMake(8.05, 2.41) controlPoint2:CGPointMake(9.68, 4.03)];
                [fill75 addCurveToPoint:CGPointMake(6.05, 9.65) controlPoint1:CGPointMake(9.68, 8.03) controlPoint2:CGPointMake(8.05, 9.65)];
                [fill75 addCurveToPoint:CGPointMake(2.42, 6.03) controlPoint1:CGPointMake(4.04, 9.65) controlPoint2:CGPointMake(2.42, 8.03)];
                [fill75 addCurveToPoint:CGPointMake(6.05, 2.41) controlPoint1:CGPointMake(2.42, 4.03) controlPoint2:CGPointMake(4.04, 2.41)];
                CGContextSaveGState(context);
                CGContextTranslateCTM(context, 83.71, 39.35);
                fill75.usesEvenOddFillRule = YES;
                [[UIColor colorWithHue:0.562 saturation:0.509 brightness:0.208 alpha:1] setFill];
                [fill75 fill];
                CGContextRestoreGState(context);
                
                CGContextRestoreGState(context);
            }
            
            CGContextRestoreGState(context);
        }
        
        CGContextRestoreGState(context);
        // End Oval (Outline Mask)
        
        //! Oval Copy
        UIBezierPath *ovalCopy = [UIBezierPath bezierPathWithOvalInRect:CGRectMake(0, 0, 144, 144)];
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 0.36, 0.36);
        CGContextSaveGState(context);
        ovalCopy.lineWidth = 8;
        CGContextBeginPath(context);
        CGContextAddPath(context, ovalCopy.CGPath);
        CGContextEOClip(context);
        [UIColor.whiteColor setStroke];
        [ovalCopy stroke];
        CGContextRestoreGState(context);
        CGContextRestoreGState(context);
        
        //! Oval Copy (Outline Mask)
        CGContextSaveGState(context);
        [ovalCopy applyTransform:CGAffineTransformMakeTranslation(0.36, 0.36)];
        [ovalCopy addClip];
        
        // Empty.
        
        CGContextRestoreGState(context);
        // End Oval Copy (Outline Mask)
        
        CGContextRestoreGState(context);
    }
    
    CGContextRestoreGState(context);
}

#pragma mark - Resizing Behavior

CGRect CTSplashCarResizingBehaviorApply(CTSplashCarResizingBehavior behavior, CGRect rect, CGRect target) {
    if (CGRectEqualToRect(rect, target) || CGRectEqualToRect(target, CGRectZero)) {
        return rect;
    }
    
    CGSize scales = CGSizeZero;
    scales.width = ABS(target.size.width / rect.size.width);
    scales.height = ABS(target.size.height / rect.size.height);
    
    switch (behavior) {
        case CTSplashCarResizingBehaviorAspectFit: {
            scales.width = MIN(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case CTSplashCarResizingBehaviorAspectFill: {
            scales.width = MAX(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case CTSplashCarResizingBehaviorStretch:
            break;
        
        case CTSplashCarResizingBehaviorCenter: {
            scales.width = 1;
            scales.height = 1;
            break;
        }
    }
    
    CGRect result = CGRectStandardize(rect);
    result.size.width *= scales.width;
    result.size.height *= scales.height;
    result.origin.x = target.origin.x + (target.size.width - result.size.width) / 2;
    result.origin.y = target.origin.y + (target.size.height - result.size.height) / 2;
    return result;
}


@end
