//
//  CTSplashCar.h
//
//  Created on 7/25/17.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;

@interface CTSplashCar : NSObject

#pragma mark - Resizing Behavior

typedef enum : NSInteger {
    CTSplashCarResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    CTSplashCarResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    CTSplashCarResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    CTSplashCarResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
} CTSplashCarResizingBehavior;

extern CGRect CTSplashCarResizingBehaviorApply(CTSplashCarResizingBehavior behavior, CGRect rect, CGRect target);

#pragma mark - Canvas Drawings

+ (void)drawArtboardWithFrame:(CGRect)targetFrame
                     resizing:(CTSplashCarResizingBehavior)resizing
                 primaryColor:(UIColor *)primaryColor;

@end
